// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/qinzj/superpowers-demo/ent/idpconnector"
)

// IdPConnector is the model entity for the IdPConnector schema.
type IdPConnector struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Issuer holds the value of the "issuer" field.
	Issuer string `json:"issuer,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// ClientSecret holds the value of the "client_secret" field.
	ClientSecret string `json:"client_secret,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IdPConnector) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case idpconnector.FieldID:
			values[i] = new(sql.NullInt64)
		case idpconnector.FieldIssuer, idpconnector.FieldClientID, idpconnector.FieldClientSecret:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IdPConnector fields.
func (ip *IdPConnector) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case idpconnector.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ip.ID = int(value.Int64)
		case idpconnector.FieldIssuer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field issuer", values[i])
			} else if value.Valid {
				ip.Issuer = value.String
			}
		case idpconnector.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				ip.ClientID = value.String
			}
		case idpconnector.FieldClientSecret:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_secret", values[i])
			} else if value.Valid {
				ip.ClientSecret = value.String
			}
		default:
			ip.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IdPConnector.
// This includes values selected through modifiers, order, etc.
func (ip *IdPConnector) Value(name string) (ent.Value, error) {
	return ip.selectValues.Get(name)
}

// Update returns a builder for updating this IdPConnector.
// Note that you need to call IdPConnector.Unwrap() before calling this method if this IdPConnector
// was returned from a transaction, and the transaction was committed or rolled back.
func (ip *IdPConnector) Update() *IdPConnectorUpdateOne {
	return NewIdPConnectorClient(ip.config).UpdateOne(ip)
}

// Unwrap unwraps the IdPConnector entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ip *IdPConnector) Unwrap() *IdPConnector {
	_tx, ok := ip.config.driver.(*txDriver)
	if !ok {
		panic("ent: IdPConnector is not a transactional entity")
	}
	ip.config.driver = _tx.drv
	return ip
}

// String implements the fmt.Stringer.
func (ip *IdPConnector) String() string {
	var builder strings.Builder
	builder.WriteString("IdPConnector(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ip.ID))
	builder.WriteString("issuer=")
	builder.WriteString(ip.Issuer)
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(ip.ClientID)
	builder.WriteString(", ")
	builder.WriteString("client_secret=")
	builder.WriteString(ip.ClientSecret)
	builder.WriteByte(')')
	return builder.String()
}

// IdPConnectors is a parsable slice of IdPConnector.
type IdPConnectors []*IdPConnector
