// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/qinzj/superpowers-demo/ent/idpconnector"
	"github.com/qinzj/superpowers-demo/ent/predicate"
)

// IdPConnectorDelete is the builder for deleting a IdPConnector entity.
type IdPConnectorDelete struct {
	config
	hooks    []Hook
	mutation *IdPConnectorMutation
}

// Where appends a list predicates to the IdPConnectorDelete builder.
func (ipd *IdPConnectorDelete) Where(ps ...predicate.IdPConnector) *IdPConnectorDelete {
	ipd.mutation.Where(ps...)
	return ipd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ipd *IdPConnectorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ipd.sqlExec, ipd.mutation, ipd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ipd *IdPConnectorDelete) ExecX(ctx context.Context) int {
	n, err := ipd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ipd *IdPConnectorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(idpconnector.Table, sqlgraph.NewFieldSpec(idpconnector.FieldID, field.TypeInt))
	if ps := ipd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ipd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ipd.mutation.done = true
	return affected, err
}

// IdPConnectorDeleteOne is the builder for deleting a single IdPConnector entity.
type IdPConnectorDeleteOne struct {
	ipd *IdPConnectorDelete
}

// Where appends a list predicates to the IdPConnectorDelete builder.
func (ipdo *IdPConnectorDeleteOne) Where(ps ...predicate.IdPConnector) *IdPConnectorDeleteOne {
	ipdo.ipd.mutation.Where(ps...)
	return ipdo
}

// Exec executes the deletion query.
func (ipdo *IdPConnectorDeleteOne) Exec(ctx context.Context) error {
	n, err := ipdo.ipd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{idpconnector.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ipdo *IdPConnectorDeleteOne) ExecX(ctx context.Context) {
	if err := ipdo.Exec(ctx); err != nil {
		panic(err)
	}
}
