// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/qinzj/superpowers-demo/ent/idpconnector"
	"github.com/qinzj/superpowers-demo/ent/predicate"
)

// IdPConnectorUpdate is the builder for updating IdPConnector entities.
type IdPConnectorUpdate struct {
	config
	hooks    []Hook
	mutation *IdPConnectorMutation
}

// Where appends a list predicates to the IdPConnectorUpdate builder.
func (ipu *IdPConnectorUpdate) Where(ps ...predicate.IdPConnector) *IdPConnectorUpdate {
	ipu.mutation.Where(ps...)
	return ipu
}

// SetIssuer sets the "issuer" field.
func (ipu *IdPConnectorUpdate) SetIssuer(s string) *IdPConnectorUpdate {
	ipu.mutation.SetIssuer(s)
	return ipu
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (ipu *IdPConnectorUpdate) SetNillableIssuer(s *string) *IdPConnectorUpdate {
	if s != nil {
		ipu.SetIssuer(*s)
	}
	return ipu
}

// SetClientID sets the "client_id" field.
func (ipu *IdPConnectorUpdate) SetClientID(s string) *IdPConnectorUpdate {
	ipu.mutation.SetClientID(s)
	return ipu
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (ipu *IdPConnectorUpdate) SetNillableClientID(s *string) *IdPConnectorUpdate {
	if s != nil {
		ipu.SetClientID(*s)
	}
	return ipu
}

// SetClientSecret sets the "client_secret" field.
func (ipu *IdPConnectorUpdate) SetClientSecret(s string) *IdPConnectorUpdate {
	ipu.mutation.SetClientSecret(s)
	return ipu
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (ipu *IdPConnectorUpdate) SetNillableClientSecret(s *string) *IdPConnectorUpdate {
	if s != nil {
		ipu.SetClientSecret(*s)
	}
	return ipu
}

// Mutation returns the IdPConnectorMutation object of the builder.
func (ipu *IdPConnectorUpdate) Mutation() *IdPConnectorMutation {
	return ipu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ipu *IdPConnectorUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ipu.sqlSave, ipu.mutation, ipu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ipu *IdPConnectorUpdate) SaveX(ctx context.Context) int {
	affected, err := ipu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ipu *IdPConnectorUpdate) Exec(ctx context.Context) error {
	_, err := ipu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ipu *IdPConnectorUpdate) ExecX(ctx context.Context) {
	if err := ipu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ipu *IdPConnectorUpdate) check() error {
	if v, ok := ipu.mutation.Issuer(); ok {
		if err := idpconnector.IssuerValidator(v); err != nil {
			return &ValidationError{Name: "issuer", err: fmt.Errorf(`ent: validator failed for field "IdPConnector.issuer": %w`, err)}
		}
	}
	if v, ok := ipu.mutation.ClientID(); ok {
		if err := idpconnector.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "IdPConnector.client_id": %w`, err)}
		}
	}
	if v, ok := ipu.mutation.ClientSecret(); ok {
		if err := idpconnector.ClientSecretValidator(v); err != nil {
			return &ValidationError{Name: "client_secret", err: fmt.Errorf(`ent: validator failed for field "IdPConnector.client_secret": %w`, err)}
		}
	}
	return nil
}

func (ipu *IdPConnectorUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ipu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(idpconnector.Table, idpconnector.Columns, sqlgraph.NewFieldSpec(idpconnector.FieldID, field.TypeInt))
	if ps := ipu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ipu.mutation.Issuer(); ok {
		_spec.SetField(idpconnector.FieldIssuer, field.TypeString, value)
	}
	if value, ok := ipu.mutation.ClientID(); ok {
		_spec.SetField(idpconnector.FieldClientID, field.TypeString, value)
	}
	if value, ok := ipu.mutation.ClientSecret(); ok {
		_spec.SetField(idpconnector.FieldClientSecret, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ipu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idpconnector.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ipu.mutation.done = true
	return n, nil
}

// IdPConnectorUpdateOne is the builder for updating a single IdPConnector entity.
type IdPConnectorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IdPConnectorMutation
}

// SetIssuer sets the "issuer" field.
func (ipuo *IdPConnectorUpdateOne) SetIssuer(s string) *IdPConnectorUpdateOne {
	ipuo.mutation.SetIssuer(s)
	return ipuo
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (ipuo *IdPConnectorUpdateOne) SetNillableIssuer(s *string) *IdPConnectorUpdateOne {
	if s != nil {
		ipuo.SetIssuer(*s)
	}
	return ipuo
}

// SetClientID sets the "client_id" field.
func (ipuo *IdPConnectorUpdateOne) SetClientID(s string) *IdPConnectorUpdateOne {
	ipuo.mutation.SetClientID(s)
	return ipuo
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (ipuo *IdPConnectorUpdateOne) SetNillableClientID(s *string) *IdPConnectorUpdateOne {
	if s != nil {
		ipuo.SetClientID(*s)
	}
	return ipuo
}

// SetClientSecret sets the "client_secret" field.
func (ipuo *IdPConnectorUpdateOne) SetClientSecret(s string) *IdPConnectorUpdateOne {
	ipuo.mutation.SetClientSecret(s)
	return ipuo
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (ipuo *IdPConnectorUpdateOne) SetNillableClientSecret(s *string) *IdPConnectorUpdateOne {
	if s != nil {
		ipuo.SetClientSecret(*s)
	}
	return ipuo
}

// Mutation returns the IdPConnectorMutation object of the builder.
func (ipuo *IdPConnectorUpdateOne) Mutation() *IdPConnectorMutation {
	return ipuo.mutation
}

// Where appends a list predicates to the IdPConnectorUpdate builder.
func (ipuo *IdPConnectorUpdateOne) Where(ps ...predicate.IdPConnector) *IdPConnectorUpdateOne {
	ipuo.mutation.Where(ps...)
	return ipuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ipuo *IdPConnectorUpdateOne) Select(field string, fields ...string) *IdPConnectorUpdateOne {
	ipuo.fields = append([]string{field}, fields...)
	return ipuo
}

// Save executes the query and returns the updated IdPConnector entity.
func (ipuo *IdPConnectorUpdateOne) Save(ctx context.Context) (*IdPConnector, error) {
	return withHooks(ctx, ipuo.sqlSave, ipuo.mutation, ipuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ipuo *IdPConnectorUpdateOne) SaveX(ctx context.Context) *IdPConnector {
	node, err := ipuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ipuo *IdPConnectorUpdateOne) Exec(ctx context.Context) error {
	_, err := ipuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ipuo *IdPConnectorUpdateOne) ExecX(ctx context.Context) {
	if err := ipuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ipuo *IdPConnectorUpdateOne) check() error {
	if v, ok := ipuo.mutation.Issuer(); ok {
		if err := idpconnector.IssuerValidator(v); err != nil {
			return &ValidationError{Name: "issuer", err: fmt.Errorf(`ent: validator failed for field "IdPConnector.issuer": %w`, err)}
		}
	}
	if v, ok := ipuo.mutation.ClientID(); ok {
		if err := idpconnector.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "IdPConnector.client_id": %w`, err)}
		}
	}
	if v, ok := ipuo.mutation.ClientSecret(); ok {
		if err := idpconnector.ClientSecretValidator(v); err != nil {
			return &ValidationError{Name: "client_secret", err: fmt.Errorf(`ent: validator failed for field "IdPConnector.client_secret": %w`, err)}
		}
	}
	return nil
}

func (ipuo *IdPConnectorUpdateOne) sqlSave(ctx context.Context) (_node *IdPConnector, err error) {
	if err := ipuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(idpconnector.Table, idpconnector.Columns, sqlgraph.NewFieldSpec(idpconnector.FieldID, field.TypeInt))
	id, ok := ipuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IdPConnector.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ipuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, idpconnector.FieldID)
		for _, f := range fields {
			if !idpconnector.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != idpconnector.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ipuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ipuo.mutation.Issuer(); ok {
		_spec.SetField(idpconnector.FieldIssuer, field.TypeString, value)
	}
	if value, ok := ipuo.mutation.ClientID(); ok {
		_spec.SetField(idpconnector.FieldClientID, field.TypeString, value)
	}
	if value, ok := ipuo.mutation.ClientSecret(); ok {
		_spec.SetField(idpconnector.FieldClientSecret, field.TypeString, value)
	}
	_node = &IdPConnector{config: ipuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ipuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idpconnector.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ipuo.mutation.done = true
	return _node, nil
}
