// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/qinzj/superpowers-demo/ent/idpconnector"
)

// IdPConnectorCreate is the builder for creating a IdPConnector entity.
type IdPConnectorCreate struct {
	config
	mutation *IdPConnectorMutation
	hooks    []Hook
}

// SetIssuer sets the "issuer" field.
func (ipc *IdPConnectorCreate) SetIssuer(s string) *IdPConnectorCreate {
	ipc.mutation.SetIssuer(s)
	return ipc
}

// SetClientID sets the "client_id" field.
func (ipc *IdPConnectorCreate) SetClientID(s string) *IdPConnectorCreate {
	ipc.mutation.SetClientID(s)
	return ipc
}

// SetClientSecret sets the "client_secret" field.
func (ipc *IdPConnectorCreate) SetClientSecret(s string) *IdPConnectorCreate {
	ipc.mutation.SetClientSecret(s)
	return ipc
}

// Mutation returns the IdPConnectorMutation object of the builder.
func (ipc *IdPConnectorCreate) Mutation() *IdPConnectorMutation {
	return ipc.mutation
}

// Save creates the IdPConnector in the database.
func (ipc *IdPConnectorCreate) Save(ctx context.Context) (*IdPConnector, error) {
	return withHooks(ctx, ipc.sqlSave, ipc.mutation, ipc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ipc *IdPConnectorCreate) SaveX(ctx context.Context) *IdPConnector {
	v, err := ipc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ipc *IdPConnectorCreate) Exec(ctx context.Context) error {
	_, err := ipc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ipc *IdPConnectorCreate) ExecX(ctx context.Context) {
	if err := ipc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ipc *IdPConnectorCreate) check() error {
	if _, ok := ipc.mutation.Issuer(); !ok {
		return &ValidationError{Name: "issuer", err: errors.New(`ent: missing required field "IdPConnector.issuer"`)}
	}
	if v, ok := ipc.mutation.Issuer(); ok {
		if err := idpconnector.IssuerValidator(v); err != nil {
			return &ValidationError{Name: "issuer", err: fmt.Errorf(`ent: validator failed for field "IdPConnector.issuer": %w`, err)}
		}
	}
	if _, ok := ipc.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "IdPConnector.client_id"`)}
	}
	if v, ok := ipc.mutation.ClientID(); ok {
		if err := idpconnector.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "IdPConnector.client_id": %w`, err)}
		}
	}
	if _, ok := ipc.mutation.ClientSecret(); !ok {
		return &ValidationError{Name: "client_secret", err: errors.New(`ent: missing required field "IdPConnector.client_secret"`)}
	}
	if v, ok := ipc.mutation.ClientSecret(); ok {
		if err := idpconnector.ClientSecretValidator(v); err != nil {
			return &ValidationError{Name: "client_secret", err: fmt.Errorf(`ent: validator failed for field "IdPConnector.client_secret": %w`, err)}
		}
	}
	return nil
}

func (ipc *IdPConnectorCreate) sqlSave(ctx context.Context) (*IdPConnector, error) {
	if err := ipc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ipc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ipc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ipc.mutation.id = &_node.ID
	ipc.mutation.done = true
	return _node, nil
}

func (ipc *IdPConnectorCreate) createSpec() (*IdPConnector, *sqlgraph.CreateSpec) {
	var (
		_node = &IdPConnector{config: ipc.config}
		_spec = sqlgraph.NewCreateSpec(idpconnector.Table, sqlgraph.NewFieldSpec(idpconnector.FieldID, field.TypeInt))
	)
	if value, ok := ipc.mutation.Issuer(); ok {
		_spec.SetField(idpconnector.FieldIssuer, field.TypeString, value)
		_node.Issuer = value
	}
	if value, ok := ipc.mutation.ClientID(); ok {
		_spec.SetField(idpconnector.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := ipc.mutation.ClientSecret(); ok {
		_spec.SetField(idpconnector.FieldClientSecret, field.TypeString, value)
		_node.ClientSecret = value
	}
	return _node, _spec
}

// IdPConnectorCreateBulk is the builder for creating many IdPConnector entities in bulk.
type IdPConnectorCreateBulk struct {
	config
	err      error
	builders []*IdPConnectorCreate
}

// Save creates the IdPConnector entities in the database.
func (ipcb *IdPConnectorCreateBulk) Save(ctx context.Context) ([]*IdPConnector, error) {
	if ipcb.err != nil {
		return nil, ipcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ipcb.builders))
	nodes := make([]*IdPConnector, len(ipcb.builders))
	mutators := make([]Mutator, len(ipcb.builders))
	for i := range ipcb.builders {
		func(i int, root context.Context) {
			builder := ipcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IdPConnectorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ipcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ipcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ipcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ipcb *IdPConnectorCreateBulk) SaveX(ctx context.Context) []*IdPConnector {
	v, err := ipcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ipcb *IdPConnectorCreateBulk) Exec(ctx context.Context) error {
	_, err := ipcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ipcb *IdPConnectorCreateBulk) ExecX(ctx context.Context) {
	if err := ipcb.Exec(ctx); err != nil {
		panic(err)
	}
}
