// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/qinzj/superpowers-demo/ent/idpconnector"
	"github.com/qinzj/superpowers-demo/ent/predicate"
)

// IdPConnectorQuery is the builder for querying IdPConnector entities.
type IdPConnectorQuery struct {
	config
	ctx        *QueryContext
	order      []idpconnector.OrderOption
	inters     []Interceptor
	predicates []predicate.IdPConnector
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IdPConnectorQuery builder.
func (ipq *IdPConnectorQuery) Where(ps ...predicate.IdPConnector) *IdPConnectorQuery {
	ipq.predicates = append(ipq.predicates, ps...)
	return ipq
}

// Limit the number of records to be returned by this query.
func (ipq *IdPConnectorQuery) Limit(limit int) *IdPConnectorQuery {
	ipq.ctx.Limit = &limit
	return ipq
}

// Offset to start from.
func (ipq *IdPConnectorQuery) Offset(offset int) *IdPConnectorQuery {
	ipq.ctx.Offset = &offset
	return ipq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ipq *IdPConnectorQuery) Unique(unique bool) *IdPConnectorQuery {
	ipq.ctx.Unique = &unique
	return ipq
}

// Order specifies how the records should be ordered.
func (ipq *IdPConnectorQuery) Order(o ...idpconnector.OrderOption) *IdPConnectorQuery {
	ipq.order = append(ipq.order, o...)
	return ipq
}

// First returns the first IdPConnector entity from the query.
// Returns a *NotFoundError when no IdPConnector was found.
func (ipq *IdPConnectorQuery) First(ctx context.Context) (*IdPConnector, error) {
	nodes, err := ipq.Limit(1).All(setContextOp(ctx, ipq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{idpconnector.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ipq *IdPConnectorQuery) FirstX(ctx context.Context) *IdPConnector {
	node, err := ipq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IdPConnector ID from the query.
// Returns a *NotFoundError when no IdPConnector ID was found.
func (ipq *IdPConnectorQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ipq.Limit(1).IDs(setContextOp(ctx, ipq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{idpconnector.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ipq *IdPConnectorQuery) FirstIDX(ctx context.Context) int {
	id, err := ipq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IdPConnector entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IdPConnector entity is found.
// Returns a *NotFoundError when no IdPConnector entities are found.
func (ipq *IdPConnectorQuery) Only(ctx context.Context) (*IdPConnector, error) {
	nodes, err := ipq.Limit(2).All(setContextOp(ctx, ipq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{idpconnector.Label}
	default:
		return nil, &NotSingularError{idpconnector.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ipq *IdPConnectorQuery) OnlyX(ctx context.Context) *IdPConnector {
	node, err := ipq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IdPConnector ID in the query.
// Returns a *NotSingularError when more than one IdPConnector ID is found.
// Returns a *NotFoundError when no entities are found.
func (ipq *IdPConnectorQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ipq.Limit(2).IDs(setContextOp(ctx, ipq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{idpconnector.Label}
	default:
		err = &NotSingularError{idpconnector.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ipq *IdPConnectorQuery) OnlyIDX(ctx context.Context) int {
	id, err := ipq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IdPConnectors.
func (ipq *IdPConnectorQuery) All(ctx context.Context) ([]*IdPConnector, error) {
	ctx = setContextOp(ctx, ipq.ctx, "All")
	if err := ipq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IdPConnector, *IdPConnectorQuery]()
	return withInterceptors[[]*IdPConnector](ctx, ipq, qr, ipq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ipq *IdPConnectorQuery) AllX(ctx context.Context) []*IdPConnector {
	nodes, err := ipq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IdPConnector IDs.
func (ipq *IdPConnectorQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ipq.ctx.Unique == nil && ipq.path != nil {
		ipq.Unique(true)
	}
	ctx = setContextOp(ctx, ipq.ctx, "IDs")
	if err = ipq.Select(idpconnector.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ipq *IdPConnectorQuery) IDsX(ctx context.Context) []int {
	ids, err := ipq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ipq *IdPConnectorQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ipq.ctx, "Count")
	if err := ipq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ipq, querierCount[*IdPConnectorQuery](), ipq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ipq *IdPConnectorQuery) CountX(ctx context.Context) int {
	count, err := ipq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ipq *IdPConnectorQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ipq.ctx, "Exist")
	switch _, err := ipq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ipq *IdPConnectorQuery) ExistX(ctx context.Context) bool {
	exist, err := ipq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IdPConnectorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ipq *IdPConnectorQuery) Clone() *IdPConnectorQuery {
	if ipq == nil {
		return nil
	}
	return &IdPConnectorQuery{
		config:     ipq.config,
		ctx:        ipq.ctx.Clone(),
		order:      append([]idpconnector.OrderOption{}, ipq.order...),
		inters:     append([]Interceptor{}, ipq.inters...),
		predicates: append([]predicate.IdPConnector{}, ipq.predicates...),
		// clone intermediate query.
		sql:  ipq.sql.Clone(),
		path: ipq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Issuer string `json:"issuer,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IdPConnector.Query().
//		GroupBy(idpconnector.FieldIssuer).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ipq *IdPConnectorQuery) GroupBy(field string, fields ...string) *IdPConnectorGroupBy {
	ipq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IdPConnectorGroupBy{build: ipq}
	grbuild.flds = &ipq.ctx.Fields
	grbuild.label = idpconnector.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Issuer string `json:"issuer,omitempty"`
//	}
//
//	client.IdPConnector.Query().
//		Select(idpconnector.FieldIssuer).
//		Scan(ctx, &v)
func (ipq *IdPConnectorQuery) Select(fields ...string) *IdPConnectorSelect {
	ipq.ctx.Fields = append(ipq.ctx.Fields, fields...)
	sbuild := &IdPConnectorSelect{IdPConnectorQuery: ipq}
	sbuild.label = idpconnector.Label
	sbuild.flds, sbuild.scan = &ipq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IdPConnectorSelect configured with the given aggregations.
func (ipq *IdPConnectorQuery) Aggregate(fns ...AggregateFunc) *IdPConnectorSelect {
	return ipq.Select().Aggregate(fns...)
}

func (ipq *IdPConnectorQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ipq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ipq); err != nil {
				return err
			}
		}
	}
	for _, f := range ipq.ctx.Fields {
		if !idpconnector.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ipq.path != nil {
		prev, err := ipq.path(ctx)
		if err != nil {
			return err
		}
		ipq.sql = prev
	}
	return nil
}

func (ipq *IdPConnectorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IdPConnector, error) {
	var (
		nodes = []*IdPConnector{}
		_spec = ipq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IdPConnector).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IdPConnector{config: ipq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ipq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ipq *IdPConnectorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ipq.querySpec()
	_spec.Node.Columns = ipq.ctx.Fields
	if len(ipq.ctx.Fields) > 0 {
		_spec.Unique = ipq.ctx.Unique != nil && *ipq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ipq.driver, _spec)
}

func (ipq *IdPConnectorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(idpconnector.Table, idpconnector.Columns, sqlgraph.NewFieldSpec(idpconnector.FieldID, field.TypeInt))
	_spec.From = ipq.sql
	if unique := ipq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ipq.path != nil {
		_spec.Unique = true
	}
	if fields := ipq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, idpconnector.FieldID)
		for i := range fields {
			if fields[i] != idpconnector.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ipq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ipq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ipq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ipq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ipq *IdPConnectorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ipq.driver.Dialect())
	t1 := builder.Table(idpconnector.Table)
	columns := ipq.ctx.Fields
	if len(columns) == 0 {
		columns = idpconnector.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ipq.sql != nil {
		selector = ipq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ipq.ctx.Unique != nil && *ipq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ipq.predicates {
		p(selector)
	}
	for _, p := range ipq.order {
		p(selector)
	}
	if offset := ipq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ipq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IdPConnectorGroupBy is the group-by builder for IdPConnector entities.
type IdPConnectorGroupBy struct {
	selector
	build *IdPConnectorQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ipgb *IdPConnectorGroupBy) Aggregate(fns ...AggregateFunc) *IdPConnectorGroupBy {
	ipgb.fns = append(ipgb.fns, fns...)
	return ipgb
}

// Scan applies the selector query and scans the result into the given value.
func (ipgb *IdPConnectorGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ipgb.build.ctx, "GroupBy")
	if err := ipgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IdPConnectorQuery, *IdPConnectorGroupBy](ctx, ipgb.build, ipgb, ipgb.build.inters, v)
}

func (ipgb *IdPConnectorGroupBy) sqlScan(ctx context.Context, root *IdPConnectorQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ipgb.fns))
	for _, fn := range ipgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ipgb.flds)+len(ipgb.fns))
		for _, f := range *ipgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ipgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ipgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IdPConnectorSelect is the builder for selecting fields of IdPConnector entities.
type IdPConnectorSelect struct {
	*IdPConnectorQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ips *IdPConnectorSelect) Aggregate(fns ...AggregateFunc) *IdPConnectorSelect {
	ips.fns = append(ips.fns, fns...)
	return ips
}

// Scan applies the selector query and scans the result into the given value.
func (ips *IdPConnectorSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ips.ctx, "Select")
	if err := ips.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IdPConnectorQuery, *IdPConnectorSelect](ctx, ips.IdPConnectorQuery, ips, ips.inters, v)
}

func (ips *IdPConnectorSelect) sqlScan(ctx context.Context, root *IdPConnectorQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ips.fns))
	for _, fn := range ips.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ips.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ips.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
