// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/qinzj/superpowers-demo/ent/oauth2client"
	"github.com/qinzj/superpowers-demo/ent/predicate"
)

// OAuth2ClientUpdate is the builder for updating OAuth2Client entities.
type OAuth2ClientUpdate struct {
	config
	hooks    []Hook
	mutation *OAuth2ClientMutation
}

// Where appends a list predicates to the OAuth2ClientUpdate builder.
func (ou *OAuth2ClientUpdate) Where(ps ...predicate.OAuth2Client) *OAuth2ClientUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetClientID sets the "client_id" field.
func (ou *OAuth2ClientUpdate) SetClientID(s string) *OAuth2ClientUpdate {
	ou.mutation.SetClientID(s)
	return ou
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (ou *OAuth2ClientUpdate) SetNillableClientID(s *string) *OAuth2ClientUpdate {
	if s != nil {
		ou.SetClientID(*s)
	}
	return ou
}

// SetClientSecret sets the "client_secret" field.
func (ou *OAuth2ClientUpdate) SetClientSecret(s string) *OAuth2ClientUpdate {
	ou.mutation.SetClientSecret(s)
	return ou
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (ou *OAuth2ClientUpdate) SetNillableClientSecret(s *string) *OAuth2ClientUpdate {
	if s != nil {
		ou.SetClientSecret(*s)
	}
	return ou
}

// SetRedirectUris sets the "redirect_uris" field.
func (ou *OAuth2ClientUpdate) SetRedirectUris(s []string) *OAuth2ClientUpdate {
	ou.mutation.SetRedirectUris(s)
	return ou
}

// AppendRedirectUris appends s to the "redirect_uris" field.
func (ou *OAuth2ClientUpdate) AppendRedirectUris(s []string) *OAuth2ClientUpdate {
	ou.mutation.AppendRedirectUris(s)
	return ou
}

// Mutation returns the OAuth2ClientMutation object of the builder.
func (ou *OAuth2ClientUpdate) Mutation() *OAuth2ClientMutation {
	return ou.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OAuth2ClientUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OAuth2ClientUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OAuth2ClientUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OAuth2ClientUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ou *OAuth2ClientUpdate) check() error {
	if v, ok := ou.mutation.ClientID(); ok {
		if err := oauth2client.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuth2Client.client_id": %w`, err)}
		}
	}
	if v, ok := ou.mutation.ClientSecret(); ok {
		if err := oauth2client.ClientSecretValidator(v); err != nil {
			return &ValidationError{Name: "client_secret", err: fmt.Errorf(`ent: validator failed for field "OAuth2Client.client_secret": %w`, err)}
		}
	}
	return nil
}

func (ou *OAuth2ClientUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ou.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauth2client.Table, oauth2client.Columns, sqlgraph.NewFieldSpec(oauth2client.FieldID, field.TypeInt))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.ClientID(); ok {
		_spec.SetField(oauth2client.FieldClientID, field.TypeString, value)
	}
	if value, ok := ou.mutation.ClientSecret(); ok {
		_spec.SetField(oauth2client.FieldClientSecret, field.TypeString, value)
	}
	if value, ok := ou.mutation.RedirectUris(); ok {
		_spec.SetField(oauth2client.FieldRedirectUris, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauth2client.FieldRedirectUris, value)
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauth2client.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OAuth2ClientUpdateOne is the builder for updating a single OAuth2Client entity.
type OAuth2ClientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuth2ClientMutation
}

// SetClientID sets the "client_id" field.
func (ouo *OAuth2ClientUpdateOne) SetClientID(s string) *OAuth2ClientUpdateOne {
	ouo.mutation.SetClientID(s)
	return ouo
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (ouo *OAuth2ClientUpdateOne) SetNillableClientID(s *string) *OAuth2ClientUpdateOne {
	if s != nil {
		ouo.SetClientID(*s)
	}
	return ouo
}

// SetClientSecret sets the "client_secret" field.
func (ouo *OAuth2ClientUpdateOne) SetClientSecret(s string) *OAuth2ClientUpdateOne {
	ouo.mutation.SetClientSecret(s)
	return ouo
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (ouo *OAuth2ClientUpdateOne) SetNillableClientSecret(s *string) *OAuth2ClientUpdateOne {
	if s != nil {
		ouo.SetClientSecret(*s)
	}
	return ouo
}

// SetRedirectUris sets the "redirect_uris" field.
func (ouo *OAuth2ClientUpdateOne) SetRedirectUris(s []string) *OAuth2ClientUpdateOne {
	ouo.mutation.SetRedirectUris(s)
	return ouo
}

// AppendRedirectUris appends s to the "redirect_uris" field.
func (ouo *OAuth2ClientUpdateOne) AppendRedirectUris(s []string) *OAuth2ClientUpdateOne {
	ouo.mutation.AppendRedirectUris(s)
	return ouo
}

// Mutation returns the OAuth2ClientMutation object of the builder.
func (ouo *OAuth2ClientUpdateOne) Mutation() *OAuth2ClientMutation {
	return ouo.mutation
}

// Where appends a list predicates to the OAuth2ClientUpdate builder.
func (ouo *OAuth2ClientUpdateOne) Where(ps ...predicate.OAuth2Client) *OAuth2ClientUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OAuth2ClientUpdateOne) Select(field string, fields ...string) *OAuth2ClientUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated OAuth2Client entity.
func (ouo *OAuth2ClientUpdateOne) Save(ctx context.Context) (*OAuth2Client, error) {
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OAuth2ClientUpdateOne) SaveX(ctx context.Context) *OAuth2Client {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OAuth2ClientUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OAuth2ClientUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OAuth2ClientUpdateOne) check() error {
	if v, ok := ouo.mutation.ClientID(); ok {
		if err := oauth2client.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuth2Client.client_id": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.ClientSecret(); ok {
		if err := oauth2client.ClientSecretValidator(v); err != nil {
			return &ValidationError{Name: "client_secret", err: fmt.Errorf(`ent: validator failed for field "OAuth2Client.client_secret": %w`, err)}
		}
	}
	return nil
}

func (ouo *OAuth2ClientUpdateOne) sqlSave(ctx context.Context) (_node *OAuth2Client, err error) {
	if err := ouo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauth2client.Table, oauth2client.Columns, sqlgraph.NewFieldSpec(oauth2client.FieldID, field.TypeInt))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuth2Client.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauth2client.FieldID)
		for _, f := range fields {
			if !oauth2client.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauth2client.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.ClientID(); ok {
		_spec.SetField(oauth2client.FieldClientID, field.TypeString, value)
	}
	if value, ok := ouo.mutation.ClientSecret(); ok {
		_spec.SetField(oauth2client.FieldClientSecret, field.TypeString, value)
	}
	if value, ok := ouo.mutation.RedirectUris(); ok {
		_spec.SetField(oauth2client.FieldRedirectUris, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauth2client.FieldRedirectUris, value)
		})
	}
	_node = &OAuth2Client{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauth2client.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
