// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/qinzj/superpowers-demo/ent/idpconnector"
	"github.com/qinzj/superpowers-demo/ent/oauth2client"
	"github.com/qinzj/superpowers-demo/ent/schema"
	"github.com/qinzj/superpowers-demo/ent/session"
	"github.com/qinzj/superpowers-demo/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	idpconnectorFields := schema.IdPConnector{}.Fields()
	_ = idpconnectorFields
	// idpconnectorDescIssuer is the schema descriptor for issuer field.
	idpconnectorDescIssuer := idpconnectorFields[0].Descriptor()
	// idpconnector.IssuerValidator is a validator for the "issuer" field. It is called by the builders before save.
	idpconnector.IssuerValidator = idpconnectorDescIssuer.Validators[0].(func(string) error)
	// idpconnectorDescClientID is the schema descriptor for client_id field.
	idpconnectorDescClientID := idpconnectorFields[1].Descriptor()
	// idpconnector.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	idpconnector.ClientIDValidator = idpconnectorDescClientID.Validators[0].(func(string) error)
	// idpconnectorDescClientSecret is the schema descriptor for client_secret field.
	idpconnectorDescClientSecret := idpconnectorFields[2].Descriptor()
	// idpconnector.ClientSecretValidator is a validator for the "client_secret" field. It is called by the builders before save.
	idpconnector.ClientSecretValidator = idpconnectorDescClientSecret.Validators[0].(func(string) error)
	oauth2clientFields := schema.OAuth2Client{}.Fields()
	_ = oauth2clientFields
	// oauth2clientDescClientID is the schema descriptor for client_id field.
	oauth2clientDescClientID := oauth2clientFields[0].Descriptor()
	// oauth2client.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauth2client.ClientIDValidator = oauth2clientDescClientID.Validators[0].(func(string) error)
	// oauth2clientDescClientSecret is the schema descriptor for client_secret field.
	oauth2clientDescClientSecret := oauth2clientFields[1].Descriptor()
	// oauth2client.ClientSecretValidator is a validator for the "client_secret" field. It is called by the builders before save.
	oauth2client.ClientSecretValidator = oauth2clientDescClientSecret.Validators[0].(func(string) error)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescToken is the schema descriptor for token field.
	sessionDescToken := sessionFields[0].Descriptor()
	// session.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	session.TokenValidator = sessionDescToken.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
