// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// IdPConnector is the predicate function for idpconnector builders.
type IdPConnector func(*sql.Selector)

// OAuth2Client is the predicate function for oauth2client builders.
type OAuth2Client func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
